version: 2
jobs:
  build:
    working_directory: ~/buendia

    docker:
      - image: projectbuendia/debian-stretch:1.1.0

    steps:
      - checkout # check out the code in the project directory

      - restore_cache:
          keys:
              - buendia-v1-{{ .Branch }}-{{ .Revision }}
              - buendia-v1-{{ .Branch }}
              - buendia-v1-

      - run:
          name: Determine package version number
          command: |
              tools/get_package_version > /tmp/buendia-version

      - run:
          name: Restore file mtimes for later package comparison
          command: git restore-mtime
          
      - run:
          name: Build all Debian packages
          command: make -C packages PACKAGE_VERSION=$(cat /tmp/buendia-version)

      - save_cache:
          key: buendia-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/.m2
            - /tmp/buendia-fetched

      - run:
          name: Collect and store test results
          # https://circleci.com/docs/2.0/collect-test-data/#maven-surefire-plugin-for-java-junit-results
          command: |
            mkdir -p /tmp/artifacts/tests/junit
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} /tmp/artifacts/tests/junit/ \;
          when: always

      - store_test_results:
          path: /tmp/artifacts/tests
             
      - run: 
          name: Collect and store built packages
          command: mkdir -p /tmp/artifacts/packages && cp $(find packages -name '*.deb') /tmp/artifacts/packages

      - store_artifacts:
          path: /tmp/artifacts

      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - packages

  apt-archive:
    working_directory: ~/buendia

    docker:
      - image: circleci/buildpack-deps:stretch

    steps:
      - run:
          name: Determine build branch and package suite
          # Decide which branch of projectbuendia/buendia to build from, by
          # checking $TARGET_BRANCH and then falling back to $CIRCLE_BRANCH.
          #
          # Then, choose the target Debian package suite based on the given
          # branch.
          #
          # See `tools/rebuild_apt_repo` for a usage example.
          #
          # https://circleci.com/docs/2.0/env-vars/#using-bash_env-to-set-environment-variables
          command: |
              TARGET_BRANCH=${BUENDIA_BRANCH:-$CIRCLE_BRANCH}
              echo "export BUENDIA_BRANCH=${TARGET_BRANCH}" >> $BASH_ENV
              if [ "${TARGET_BRANCH}" = "master" ]; then
                echo "export BUENDIA_SUITE=stable" >> $BASH_ENV
              elif [ "${TARGET_BRANCH}" = "dev" ]; then
                echo "export BUENDIA_SUITE=unstable" >> $BASH_ENV
              else
                echo "Can only rebuild the apt archive for the 'master' or 'dev' branch!"
                exit 1
              fi

      - checkout # check out the code in the project directory

      - attach_workspace:
          at: /tmp/artifacts

      - run:
          name: Fetch latest artifacts (if not already present)
          command: |
              PACKAGES=/tmp/artifacts/packages
              if [ ! -d $PACKAGES -a -n "${CIRCLE_API_TOKEN}" ]; then
                echo "Build triggered manually by ${CIRCLE_USERNAME}; fetching artifacts from latest ${BUENDIA_BRANCH} build job."
                mkdir -p $PACKAGES && cd $PACKAGES
                $HOME/buendia/tools/fetch_circleci_artifacts projectbuendia/buendia ${BUENDIA_BRANCH} '*.deb'
              fi

      - restore_cache:
          keys:
            - buendia-builds-v1-{{ .Branch }}-{{ .Revision }}
            - buendia-builds-v1-{{ .Branch }}
            - buendia-builds-v1-

      - add_ssh_keys:
          fingerprints:
            - "18:e2:e2:8e:12:49:a1:ca:e6:6f:e1:30:08:02:ae:43"

      - run:
          name: Get the latest builds repository
          ### NOTE: this job must have a key that can read AND write to
          ### github.com/projectbuendia/builds
          command: |
            [ -d builds ] || git clone git@github.com:projectbuendia/builds
            cd builds && \
                  git fetch --force origin gh-pages && \
                  git reset --hard origin/gh-pages && \
                  git checkout -q -B gh-pages

      - run:
          name: Configure the Git user
          command: |
              git config --global user.name "CircleCI Build Process"
              git config --global user.email "zestybuendia@gmail.com"

      - run:
          name: Install apt-utils
          command: sudo apt-get update && sudo apt-get -y install apt-utils

      - run:
          name: Update the package archive
          command: tools/update_apt_archive builds/packages ${BUENDIA_SUITE} /tmp/artifacts/packages

      - save_cache:
          key: buendia-builds-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/buendia/builds/.git

      - store_artifacts:
          # Carry forward the artifacts from the previous build job
          path: /tmp/artifacts

workflows:
  version: 2
  normal-build:
    jobs:
      - build
      - apt-archive:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - dev
